services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-compose
    restart: always
    environment:
      REDIS_ARGS: "--requirepass systempass" # 기본사용자 이름 default
    ports:
      - 6379:6379
      - 8001:8001