@orderId=3f3303ab-3f03-4f48-902e-57bd76b85ac4
@articleId=1

### 1. 주문 생성 (POST)
POST http://localhost:8080/orders
Content-Type: application/json

{
  "item": "mouse",
  "count": 5,
  "totalPrice": 100000,
  "status": "PENDING"
}


### 2. 모든 주문 조회 (GET)
GET http://localhost:8080/orders
Accept: application/json


### 3. 특정 주문 조회 (GET)
GET http://localhost:8080/orders/{{orderId}}
Accept: application/json


### 4. 주문 수정 (PUT)
PUT http://localhost:8080/orders/{{orderId}}
Content-Type: application/json

{
  "item": "Monitor",
  "count": 2,
  "totalPrice": 250000,
  "status": "DELIVERED"
}


### 5. 주문 삭제 (DELETE)
DELETE http://localhost:8080/orders/{{orderId}}


### 6. 조회수 증가(GET)
GET http://localhost:8080/articles/{{articleId}}
